# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: APP

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install sshpass -y

    - name: Securely copy databases from remote server
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" scp -r "ec2-user@3.92.50.187:/home/ec2-user/zhilservice/admin/databases/*" ./admin/databases/
